### ISSUE TITLE
Не могу установить ваш SDK  на Python 2.7

### ISSUE THREAD

**Issue by roxt-underground** [Platron/python-sdk#1]
> pip install platron_sdk
>
> Collecting platron_sdk
>
>   Could not find a version that satisfies the requirement platron_sdk (from versions: )
>
> No matching distribution found for platron_sdk
>

**Comment by zeggel** [comment]
Здравствуйте.

Видимо опечатка, попробуйте "pip install platron"

**Comment by lashnag** [comment]
Обновили версию для поддержки 54ФЗ (создание чеков)
https://pypi.python.org/pypi/platron/2.0.0
