### ISSUE TITLE
Не поддерживается константа для 20% налога в чеке

### ISSUE THREAD

**Issue by kirillmakhonin** [Platron/python-sdk#2]
При попытке отправить чек, необходимо указывать валидную константу для метода `add_vat`, однако валидные константы не поддерживают НДС 20%, а поддерживают только НДС 10/18%.

https://github.com/Platron/python-sdk/blob/master/platron/request/data_objects/item.py#L70

Как временное решение до фикса можно использовать прямую установку python атрибута:
```
item.pg_vat = '20'
```

**Comment by lashnag** [comment]
Добрый день! Приношу прощения за то, что опоздали с обновлением SDK. Так как 18% больше не поддерживается - то придется обновить мажорную версию пакета по причине того, что она не совместима с текущей...
